# Generated by Django 4.2.16 on 2024-09-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_firstname', models.CharField(max_length=64)),
                ('requestor_lastname', models.CharField(max_length=64)),
                ('requestor_email', models.CharField(max_length=64)),
                ('pi_firstname', models.CharField(max_length=64)),
                ('pi_lastname', models.CharField(max_length=64)),
                ('pi_email', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srm_order', models.IntegerField()),
                ('srm_sample', models.IntegerField()),
                ('samplename', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
                ('sequencer', models.CharField(max_length=64)),
                ('runtype', models.CharField(max_length=64)),
                ('readlength', models.CharField(max_length=64)),
                ('referencegenome', models.CharField(max_length=64)),
                ('humanderived', models.BooleanField()),
                ('tb_number', models.CharField(max_length=64)),
                ('sjuid_sample', models.CharField(max_length=64)),
                ('bampath', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
