# Generated by Django 4.2.16 on 2024-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0002_rename_application_sample_assay_remove_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='srm_order',
            field=models.IntegerField(),
        ),
    ]
