# Generated by Django 4.2.16 on 2024-09-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0003_order_id_alter_order_srm_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='humanderived',
            new_name='ishumanderived',
        ),
    ]
