# Generated by Django 4.2.16 on 2024-09-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0005_sample_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='omicsbackend.order'),
        ),
    ]
