# Generated by Django 4.2.16 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0006_alter_sample_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='srm_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='srm_sample',
            field=models.IntegerField(unique=True),
        ),
    ]
