# Generated by Django 4.2.16 on 2024-09-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0007_alter_order_srm_order_alter_sample_srm_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sjuid_subject',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sjuid_sample',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
