# Generated by Django 4.2.16 on 2024-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0008_sample_sjuid_subject_alter_sample_sjuid_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='assay',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
