# Generated by Django 4.2.16 on 2024-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omicsbackend', '0010_alter_order_order_date_alter_order_pi_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='compbioid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
